[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']
runner = "wasm-server-runner"

[unstable]
build-std = ["core", "alloc", "std", "panic_abort"]
build-std-features = []
