[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-feature=+crt-static"]

[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']
runner = "wasm-server-runner"

[unstable]
build-std = ["core", "alloc", "std", "panic_abort"]
build-std-features = []
