[target.x86_64-pc-windows-msvc]
linker = "lld"
rustflags = [
  "-Lnative=/home/kaleb/.xwin/crt/lib/x86_64",
  "-Lnative=/home/kaleb/.xwin/sdk/lib/um/x86_64",
  "-Lnative=/home/kaleb/.xwin/sdk/lib/ucrt/x86_64",
  "-Ctarget-feature=+crt-static",
]

[target.i686-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']
runner = "wasm-server-runner"

[unstable]
build-std = ["core", "alloc", "std", "panic_abort"]
build-std-features = []
